name: Selenium C# CI
on: 
  schedule: 
    - cron: '0 0 * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release
      - name: Run Selenium Tests
        run: dotnet test --filter Category=Integration
            
        
  
