name: Selenium C# CI
on: 
  schedule: 
    - cron: '9 * * * *'
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 4.7.2
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dot net build --configuration Release
      - name: Run Selenium Tests
        run: dotnet test --filter Category=Integration
            
        
  
